name: "ghav before: main"
"on":
  push:
    branches:
      - ghav/dev/513
    paths:
      - .ghav/before
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - ^20
          - ^22
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn coverage
